project:
  type: book
  output-dir: "_site"

book:
  title: "DrugUtilisation Studies in the OMOP Common Data Model"
  author:
    - name: Martí Català
  date: today
  chapters:
    - index.qmd
    - introduction.qmd
    - structure.qmd

#bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    titlepage: formal
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    keep-tex: true
