project:
  type: book
  output-dir: "_site"

book:
  title: "Drug Utilisation Studies in the OMOP Common Data Model"
  author:
    - name: Martí Català
  date: today
  chapters:
    - index.qmd
    - structure.qmd
    - part: introduction/index.qmd
      chapters:
        - introduction/drug_data_omop.qmd
    - final_remarks.qmd

#bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    titlepage: formal
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    keep-tex: true
