# Proposed structure for the book

-   Preface
    -   Is this book for me
        -   OMOP
        -   R
        -   Tidyverse
        -   Tidy R in OMOP CDM collection
        -   Set up your environment
    -   About the authors
-   Introduction
    -   Drug Utilisation studies
    -   Drug data in the OMOP CDM
    -   Drug vocabularies
    -   Dose form and routes
    -   Standard vs source
    -   Synthetic data used
-   Drug Users identification
    -   Create drug codelists
        -   Stratify and subset codelists
        -   Drug combination codelists
        -   Import and export codelists
    -   Diagnostics
        -   PhenotypeR
        -   Dose calculation
    -   Identify users
        -   Drug users cohort
        -   Identify new users
        -   Concatenation of prescriptions
-   Population level DrugUtilisation
    -   Denominator cohort
        -   General Population
        -   Target Population
        -   External Denominator
    -   Incidence
        -   Standardised Incidence Rate
        -   Incidence Rate Ratio
        -   Standardised Incidence Rate Ratio
    -   Prevalence
        -   Point Prevalence
        -   Period Prevalence
-   Patient level DrugUtilisation
    -   New users characterisation
        -   Characterisation
        -   Large Scale Characteristics (Data Driven Characterisation)
    -   Indication
        -   Indication in the data base
        -   Phenotype Driven indication
        -   Data Driven indication
        -   Linked indication
    -   Drug use
        -   How to calculate daily dose?
        -   Summarise drug use
    -   Treatments
        -   Alternative treatments
        -   Comedications
    -   Discontinuation
        -   As survival
        -   Proportion of patients covered
        -   Multistate analysis
    -   Drug switching
        -   Drug restart and drug switching
        -   Treatment pathways
        -   Multi-state
    -   Dose escalation
        -   Dose summary
        -   Dose pathways
        -   Dose states
-   DrugUtilisation study
    -   Final considerations
    -   Examples of DrugUtilisation Studies
    -   Other studies

```{r}
library(DrugUtilisation)
library(omock)
```
